import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";


// Helper to recursively bundle CSS @import statements
function bundleCSS(entryPath) {
	const content = fs.readFileSync(entryPath, "utf8");
	const dir = path.dirname(entryPath);
	return content.replace(/@import\s+["'](.+?)["'];/g, (match, importPath) => {
		const fullPath = path.resolve(dir, importPath);
		return bundleCSS(fullPath);
	});
}

// Bundle CSS entrypoint: main.css -> dist/styles.css
function buildStyles() {
	if (!fs.existsSync("dist")) {
		fs.mkdirSync("dist");
	}
	try {
		const bundled = bundleCSS("src/styles/main.css");
		fs.writeFileSync("dist/styles.css", bundled);
		fs.copyFileSync("manifest.json", "dist/manifest.json");
		console.log("Built dist/styles.css and dist/manifest.json");
	} catch (err) {
		console.error("Error building styles:", err);
	}
}


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",

	minify: prod,
});

if (prod) {
	buildStyles();
	await context.rebuild();
	process.exit(0);
} else {
	buildStyles();
	// Watch for CSS changes recursively in src/styles
	try {
		fs.watch("src/styles", { recursive: true }, buildStyles);
	} catch (err) {
		console.warn("Could not watch src/styles recursively, falling back to files:", err.message);
		fs.watch("src/styles/fonts.css", buildStyles);
	}
	await context.watch();
}
